name: Build
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          check-latest: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run test
      - name: Lint code
        run: yarn run lint
      - name: Code coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true